### ISSUE TITLE
duplicate shape [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/ecpo-annotator#34] opened 2019-12-12 17:05 UTC
The original issue

	Id: 33
	Title: duplicate shape

could not be created.
This is a dummy issue, replacing the original one. It contains everything but the original issue description. In case the gitlab repository is still existing, visit the following link to show the original issue:

TODO

**Comment by line-o** [comment] 2020-03-25 11:02
This issue seems to be a duplicate of #33

**Closed** 2020-03-25 13:15 UTC
Labels: duplicate
